"""
crypttab generation module.

This module handles generating crypttab entries for encrypted partitions.
"""
import os
import logging
from typing import Dict, Any
from pathlib import Path

from architect.utils.command import CommandRunner, SimulationMode
from architect.core.exceptions import CrypttabError

logger = logging.getLogger('architect')


def generate_crypttab(partitions: Dict[str, str], disk_info: Dict[str, Any], args: Any, cmd_runner: CommandRunner) -> None:
    """
    Generate crypttab in target directory.
    
    Args:
        partitions: Dict mapping partition roles to device paths
        disk_info: Dict containing disk info
        args: Command line arguments
        cmd_runner: CommandRunner instance for executing commands
        
    Raises:
        CrypttabError: If there's an error in crypttab generation
    """
    if not args.generate_crypttab or "system_crypt" not in partitions:
        return
    
    target = args.target
    target_path = Path(target)
    etc_path = target_path / "etc"
    crypttab_path = etc_path / "crypttab"
    
    # Create etc directory if it doesn't exist
    if cmd_runner.simulation_mode == SimulationMode.SIMULATE:
        logger.info(f"Would create directory: {etc_path}")
    else:
        etc_path.mkdir(exist_ok=True)
    
    logger.info(f"Generating crypttab at {crypttab_path}")
    
    try:
        # Get device PARTUUID for the encrypted partition
        encrypted_partuuid = cmd_runner.run(["blkid", "-s", "PARTUUID", "-o", "value", partitions["system_crypt"]]).stdout.strip()
        luks_name = os.path.basename(partitions["system"])
        
        # Build crypttab content
        crypttab_content = []
        crypttab_content.append("# /etc/crypttab: mappings for encrypted partitions.")
        crypttab_content.append("# Generated by the architect")
        crypttab_content.append("#")
        crypttab_content.append("# <target name> <source device> <key file> <options>")
        
        # Determine crypttab options based on disk type
        options = "luks,timeout=180"
        
        # Add discard only for SSDs with TRIM support
        if not disk_info["rotational"] and disk_info.get("trim_supported", False):
            logger.info("Adding discard option to crypttab (SSD with TRIM support)")
            options += ",discard"
        elif not disk_info["rotational"]:
            logger.info("SSD detected but TRIM support not confirmed, not adding discard option to crypttab")
        
        # Add line for our LUKS device
        crypttab_content.append(f"{luks_name} PARTUUID={encrypted_partuuid} none {options}")
        
        # Write crypttab or display it in simulation mode
        if cmd_runner.simulation_mode == SimulationMode.SIMULATE:
            logger.info("Would write the following to crypttab:")
            for line in crypttab_content:
                logger.info(f"  {line}")
        else:
            with open(crypttab_path, "w") as f:
                f.write("\n".join(crypttab_content) + "\n")
        
        logger.info("crypttab generated successfully")
    except Exception as e:
        raise CrypttabError(f"Failed to generate crypttab: {e}")
