"""
fstab generation module.

This module handles generating optimized fstab entries for the target system.
"""
import os
import logging
from typing import Dict, Any
from pathlib import Path

from architect.utils.command import CommandRunner, SimulationMode
from architect.core.exceptions import FstabError

logger = logging.getLogger('architect')


def generate_fstab(partitions: Dict[str, str], mount_options: Dict[str, str], args: Any, cmd_runner: CommandRunner) -> None:
    """
    Generate fstab in target directory.
    
    Args:
        partitions: Dict mapping partition roles to device paths
        mount_options: Dict mapping mount points to their mount options
        args: Command line arguments
        cmd_runner: CommandRunner instance for executing commands
        
    Raises:
        FstabError: If there's an error in fstab generation
    """
    if not args.generate_fstab:
        return
    
    target = args.target
    target_path = Path(target)
    etc_path = target_path / "etc"
    fstab_path = etc_path / "fstab"
    
    # Create etc directory if it doesn't exist
    if cmd_runner.simulation_mode == SimulationMode.SIMULATE:
        logger.info(f"Would create directory: {etc_path}")
    else:
        etc_path.mkdir(exist_ok=True)
    
    logger.info(f"Generating fstab at {fstab_path}")
    
    try:
        # Get device PARTUUIDs and UUIDs
        efi_partuuid = cmd_runner.run(["blkid", "-s", "PARTUUID", "-o", "value", partitions["efi"]]).stdout.strip()
        boot_partuuid = cmd_runner.run(["blkid", "-s", "PARTUUID", "-o", "value", partitions["boot"]]).stdout.strip()
        system_uuid = cmd_runner.run(["blkid", "-s", "UUID", "-o", "value", partitions["system"]]).stdout.strip()
        
        # Build fstab content
        fstab_content = []
        fstab_content.append("# /etc/fstab: static file system information.")
        fstab_content.append("# Generated by the architect")
        fstab_content.append("#")
        fstab_content.append("# <file system> <mount point> <type> <options> <dump> <pass>")
        
        # Include LUKS device if using software encryption
        if "system_crypt" in partitions:
            crypt_partuuid = cmd_runner.run(["blkid", "-s", "PARTUUID", "-o", "value", partitions["system_crypt"]]).stdout.strip()
            luks_name = os.path.basename(partitions["system"])
            fstab_content.append("# LUKS encrypted partition")
            fstab_content.append("")
        
        # Root
        root_options = mount_options["/"]
        if root_options == "defaults":
            root_options = "subvol=@"
        else:
            root_options = f"subvol=@,{root_options}"
        fstab_content.append(f"UUID={system_uuid} / btrfs {root_options} 0 0")
        
        # Boot
        boot_options = mount_options["/boot"]
        fstab_content.append(f"PARTUUID={boot_partuuid} /boot ext4 {boot_options} 0 2")
        
        # EFI
        efi_options = mount_options["/boot/efi"]
        fstab_content.append(f"PARTUUID={efi_partuuid} /boot/efi vfat {efi_options} 0 2")
        
        # Other subvolumes
        for subvol, mountpoint in {
            "@home": "/home",
            "@opt": "/opt",
            "@root": "/root",
            "@srv": "/srv",
            "@tmp": "/tmp",
            "@usr": "/usr",
            "@var": "/var",
            "@var_log": "/var/log",
            "@var_tmp": "/var/tmp"
        }.items():
            options = mount_options[mountpoint]
            if options == "defaults":
                options = f"subvol={subvol}"
            else:
                options = f"subvol={subvol},{options}"
            fstab_content.append(f"UUID={system_uuid} {mountpoint} btrfs {options} 0 0")
        
        # Add proc with hidepid=2 if in hardened mode
        if args.hardened:
            fstab_content.append("")
            fstab_content.append("# Secured /proc mount with process hiding")
            fstab_content.append("proc /proc proc hidepid=2,gid=proc 0 0")
        
        # Write fstab or display it in simulation mode
        if cmd_runner.simulation_mode == SimulationMode.SIMULATE:
            logger.info("Would write the following to fstab:")
            for line in fstab_content:
                logger.info(f"  {line}")
        else:
            with open(fstab_path, "w") as f:
                f.write("\n".join(fstab_content) + "\n")
        
        logger.info("fstab generated successfully")
    except Exception as e:
        raise FstabError(f"Failed to generate fstab: {e}")
